### ISSUE TITLE
Exactly once guarantee

### ISSUE THREAD

**Issue by ebrard** [Zooz/kafka-s3-connector#2]
Hi,
What happens if a file is uploaded to S3 but the commit (of the offsets) to Kafka fails and the service crash/is restarted? In this situation, wouldn't I get some duplicated Kafka message in the file outputs? I couldn't see where in the code you guard against this.

**Comment by guybiecher** [comment]
Hi Emmanuel,
we create the files name in s3 by the following format {partition_number}_{offset} which means if we wouldn't commit the offset for some reason the next time we will need to flush those files we will overwrite the files in s3 because they have the same names.

**Comment by ebrard** [comment]
So this means that in case of failure and new activity on a topic, the file content will be different after the "second" upload, right?

**Comment by guybiecher** [comment]
Right the content could be different.

**Comment by ebrard** [comment]
All right, thank you for the information.
